first yaml

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -11,6 +11,8 @@ jobs:
   say-goodbye:
     runs-on: ubuntu-latest
     steps:
-      - name: Say Goodbye
-        run: echo "Goodbye!"
+      - name: Failed step
+        run: |
+          echo "I will fail"
+          exit 1
     
